### ISSUE TITLE
ChecksumCCITT wrong results

### ISSUE THREAD

**Issue by bytecorner-jan** [howeyc/crc16#4]
Hello, 

I just tested the library and got Strange results: 
for the "payloads" I have expected values for 
[]byte{0x04} -> expected 0x40, 0x84 -> Result B6 5C
[]byte{0x08, 0x00, 0x00, 0x01, 0xF4} -> expected 0x9E, 0x87 -> Result 3D 24 

I have double checked my expectations https://www.lammertbies.nl/comm/info/crc-calculation.html

I different crc implemention proofed my results.  

Here my sample: 

package main

import (
	"fmt"

	"github.com/howeyc/crc16"
)

func main() {
	payload := []byte{0x04}
	cs := crc16.ChecksumCCITT(payload)
	fmt.Printf("Checksum: %x", cs)

}

**Comment by howeyc** [comment]
I'm tempted to update the library, but I'm unsure if I'd break someone's expectation if I do. So here's how to get what you want:

```go
package main

import (
	"fmt"

	"github.com/howeyc/crc16"
)

func main() {
	payload := []byte{0x08, 0x00, 0x00, 0x01, 0xF4}
	table := crc16.MakeBitsReversedTable(crc16.CCITTFalse)
	cs := crc16.Update(0, table, payload)
	fmt.Printf("Checksum: %x", cs)
}
```
