### ISSUE TITLE
How do I perform a ARK (aka CRC-16, CRC-IBM)?

### ISSUE THREAD

**Issue by jdizzle** [howeyc/crc16#5]
It seems like it *should* be the IBM checksum, but I cannot get the library to produce sane values.  I am comparing with results from here:
https://www.lammertbies.nl/comm/info/crc-calculation.html
and here:
http://www.zorc.breitbandkatze.de/crc.html

Easiest to compare is the "check" value from the description here:
http://reveng.sourceforge.net/crc-catalogue/all.htm

ascii string "123456789" should checksum to 0xbb3d

**Comment by howeyc** [comment]
Unfortunately when I created this I naively made it work for MODBUS and assumed that was the same as IBM based on Wikipedia. It's caused questions like this and will probably do so in the future. I'm tempted to create a new version that matches names/values/whatever with some of the links you've posted or other implementations but as people are using this as-is I'm inclined to just keep it as it stands.

Check the TestARC function for how to get the value you desire.
